apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla
spec:
  agentVersion: 3.1.0
  version: 5.2.11
  developerMode: true
  automaticOrphanedNodeCleanup: true
  sysctls:
  - "fs.aio-max-nr=30000000"
  datacenter:
    name: us-east-1
    racks:
    - name: us-east-1a
      members: 1
      storage:
        capacity: 500Mi
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          cpu: 1
          memory: 1Gi
